# Generated by Django 4.1 on 2022-10-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('contact', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('requirement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisplayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('text_desc', models.CharField(max_length=100)),
                ('image_display', models.ImageField(upload_to='Display_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=100)),
                ('r_image', models.ImageField(upload_to='resort_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BunglowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunglow_name', models.CharField(max_length=100)),
                ('room_size', models.CharField(max_length=100)),
                ('amenites', models.CharField(max_length=100)),
                ('images', models.FileField(upload_to='Bunglow_Images/')),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MA.displaylocation')),
            ],
        ),
    ]
